import './globals.css'
import './style.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Exo+2&family=Roboto:ital@1&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        Common Layout
        {children}
      </body>
    </html>
  )
}
